version: '3.8'

services:
  app:
    build:
      context: .
      args:
        USER_ID: ${DOCKER_USER_ID}
        USER_NAME: ${DOCKER_USER_NAME}
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mezzio-learning
      MYSQL_USER: mezzio-app
      MYSQL_PASSWORD: mezziopassword
      MYSQL_ROOT_PASSWORD: mezziorootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
